### ISSUE TITLE
Afbeeldingen worden niet getoont bij een privé netwerk

### ISSUE THREAD

**Issue by kooistrag** [ColdTrick/digest#2]
Bij een privé netwerk worden de afbeeldingen in de digest niet getoond.
Dit is te begrijpen, aangezien de afbeeldingen zonder te zijn ingelogd niet toegankelijk zijn.

Echter zorgt dit wel voor een vreemd uiterlijk, voornamelijk in Outlook.

Wellicht is het een idee om bij een privé netwerk de afbeeldingen niet te laten tonen in de digist, indien mogelijk.

**Comment by jdalsem** [comment]
Dit is opgelost in de onderliggende plugin html_email_handler https://github.com/ColdTrick/html_email_handler/commit/51817caa5b4705d685de008fbcd1cfc052619540
