### ISSUE TITLE
Add a hook to enable blocking email for specific users

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/digest#28]
I think it could be useful to have a hook triggered in the digest sending process, that would enable to block sending an email to a user, based on other parameters than the default. Currently the digest doesn't pass through the send,email hook so there is no clean way to block digest email sending for a specific user.

Standard use cases would be when using different profile type or role, or also paid membership, and we don't want to send the digest to some of theses users, based or various metadata.
The digest sending system blocks sending based on "hardcoded" parameters : personal settings + group/site setting + banned users ; but there is no easy way to check for other metadata or context to fit custom installations.

I'm not sure where a such hook should be added to fit most use cases : 
- **at the very end, in digest_send_mail** : that means a lot of computation before, and we don't know much about the context (group or site digest ?), but that's efficient for general email blocking based on parameters that are tied to the user
- **on the other side, in digest_get_site_users and digest_get_group_users** (at the end) : this allows very fine tuning based all together on digest context, interval settings and user-specific metadata, and also to _add_ new users that should be notified whatever their settings. But this probably makes it less easier for developers to implement the hook because it implies to rewrite the SQL query, or loop through the results to remove some users.
- a "middle" solution would be to add the hook to digest_group and digest_site functions (at the beggining), which is less powerful than (2), but still more than (1) because we have some context and also the ElggUser entity which makes processing easier than direct SQL, but does not enable to add new users to the digest.
- finally an alternate solution would be to use a function that passes through the send,email hook instead of a direct call to html_email_handler_send_email OR add a hook to html_email_handler_send_email function.

As my current use case is only about blocking email sending to some users because they are still active (not banned nor disabled), have an email, but are not allowed to receive notifications or any email, any of these solutions would fit.

Is it something you think might be worth to add in future releases ?  If you're interested and we agree on an implementation this is a feature i can work on :)

**Comment by jdalsem** [comment]
i think digest should be reworked to make use of the correct elgg functions so elgg hooks will be trigger to influence recipients.. i do not have a clear image on how we should be doing that
