### ISSUE TITLE
Is Packagist auto-update hook missing?

### ISSUE THREAD

**Issue by juho-jaakkola** [ColdTrick/digest#32]
The plugin has a lot of releases at Github: https://github.com/ColdTrick/digest/releases

However only `dev-master` is present at Packagist: https://packagist.org/packages/coldtrick/digest

Is the auto-update hook possibly missing from the repository settings?

**Comment by jeabakker** [comment]
composer support was only added on master and has not yet been releases in a version, so that's probably why Packagist doesn't see it.

Update hooks are configured and working

**Comment by juho-jaakkola** [comment]
Ah, of course. Somehow I assumed the tags starting with `2` are meant for Elgg `2.x`, but this is not the case.
