### ISSUE TITLE
Test page using default instead of monthly interval

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/digest#33]
There is an unexpected behaviour in the test page, which displays all content since the origin of (unix) time, which happens to lead to memory overflow in some use case (i add a module which list all changes in user groups since latest digest).

The reason is that the switch uses a comparison between a variable and a constant, which always fails and defaults to the "default" option, which sets $ts_lower to 1.

So the fix is pretty easy (and i will submit it soon for branches elgg_18 and master), but this switch behaviour can be quite disturbing...

**Comment by Facyla** [comment]
Ok, i was wrong : the cause of the error was that $interval is overrided by $page[2], which may be empty => switch uses default, which sets $interval to 'monthly', but lower TS to 1. I think that for consistency reson if $interval is set to monthly, 'monthly' case and 'default' should be merged and use the same interval.

**Comment by jeabakker** [comment]
If my thinking is correct this problem only occurs if you go to `http://example.com/digest/test/`, not if you go to `http://example.com/digest/test` correct??

in that case we could fix it here https://github.com/ColdTrick/digest/blob/master/classes/ColdTrick/Digest/Router.php#L22, by changing it to 
`$vars['interval'] = elgg_extract(2, $page, DIGEST_INTERVAL_MONTHLY, false);`

**Comment by Facyla** [comment]
Well, i've detected the problem on Digest version 3.0 on Elgg 1.12, and had
not checked the router code, which apparently limits the problem scope.

So i've just tested on Elgg 2.3 with latest version and got these results :

   - same OK result on the 3 following :  digest/test   digest/test/   and
   digest/test/monthly => all default to site and monthly digest
   - OK with digest/site and digest/site/ => default to monthly too
   ($page[2] is not set if empty url segment)
   - KO if using an invalid interval, eg. digest/site/otherinterval =>
   passes to switch default

So indeed the scope is much smaller than on the latest Elgg 1.12-compatible
version, where the default test page (digest/test)  would have the issue :
here there is no issue if no interval is set, and it only happens if the
interval is set to a non-handled value.

=> So yes, adding a strict flag would do the trick.


Still, i'd adjust this part in the resources/test view switch so the
interval and computed timestamp match :

    default:
        $interval = DIGEST_INTERVAL_MONTHLY;
        $ts_lower = 1;

=> whether set the interval to 'epoch' or something, or compute the same
$ts_lower as for monthly interval.


(sorry, what a thread for a boolean !-)



-- 
Florian DANIEL aka @Facyla <http://twitter.com/Facyla>~ Conseil en
stratégie et développement web social ~ i.daniel.florian@gmail.com ~ skype
idf-atoll ~ +33 6 70 17 98 35
Site http://facyla.fr/ ~ LinkedIn https://www.linkedin.com/in/facyla


2017-11-30 9:56 GMT+01:00 Jerôme Bakker <notifications@github.com>:
