### ISSUE TITLE
Users report vast numbers of digest mails

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/digest#39]
I have had 2 users report to me that they are receiving very large numbers of emails from the digest on my site. I have disabled their digest for now. I notice that on my live site there is no data / reports in the statistics panel for digest, but it does show up in my test site ok.
I will dig around to try to find out what the problem is here, but any help I can get is welcome.
I have looked in the mail logs but I can't see any mails coming from postfix to the address involved.

**Comment by propertunist** [comment]
Ah I can see that there is a permissions problem stopping the mail data being logged:
```
(/var/log/php-mail.log): failed to open stream: Permission denied" in file /var/www/html/mysite/mod/html_email_handler/lib/functions.php (line 277)
```
i will set the maillog file to be owned by nginx, maybe that will fix that at least

**Comment by propertunist** [comment]
I can see in the nginx log that the same mail appears to be being sent repeatedly to the same users ever 90 seconds or so. Could that be due to the permissions error in some way?

**Comment by jeabakker** [comment]
as far as i can see if a mail is failed to be sent it just gets logged, not retried. So there shouldn't be any problem with repeating users.

Could it be that the mail does end up in a mail queue (from postfix or whatever mail program you're using) and in processing the queue it doesn't get removed from the queue and thus redelivered?

**Comment by propertunist** [comment]
Hey! I don't know - but I don't have this problem with postfix in any other situation. Maybe the items are getting added to the digest list more than once for some reason?
I'm thinking that maybe the fact that the digest stats page is empty is a clue.

**Comment by propertunist** [comment]
update: I am still getting notifications from yahoo that mails are bouncing from my server, even after disabling the digest plugin

**Comment by propertunist** [comment]
oh, these appear to be related to the original mails that were sent out 3 days ago.. i am just seeing multiple bounce messages for some reason.
